name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
      - name: Install global dependencies
        run: pnpm i -g @antfu/ni
      - name: Install Dependencies
        run: npm pkg delete scripts.prepare && nci
      - name: Test
        run: nr test
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
